[tool.poetry]
name = "maslib"
version = "0.1.0"
description = "Multiagent Framework"
authors = ["contact@bayeslabs.co"]
readme = "README.md"

package-mode = true
packages = [
    { include = "maslib" }
]

[tool.poetry.dependencies]
python = "^3.12"
ipykernel = "^6.29.5"
pydantic = "^2.10.1"
litellm = "^1.53.1"
together = "^1.3.5"
ipython = "^8.31.0"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
